logging:
  config: classpath:logback-console.xml

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.77:3306/delivery_service"
    username: "hwang"
    password: "5510"
  redis:
    host: 127.0.0.77
    port: 6379
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 5510

url:
  ui: http://localhost:8080
---

spring:
  config:
    activate:
      on-profile: server
server:
  port: 5511

url:
  ui: http://localhost:8081
---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

---

spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url:  jdbc:h2:tcp://localhost/./datajpa;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: h2