server:
  port: 5510
logging:
  config: classpath:logback-console.xml

datasource:
  url: "jdbc:mysql://192.168.100.1:3306/delivery_service"
  username: "hwang"
  password: "5510"

persistenceName: jpa-mysql


---

spring:
  config:
    activate:
      on-profile: jpa-test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:

datasource:
  url: jdbc:h2:mem:test;MODE=MySQL
  username: sa
  password:

persistenceName: jpa-test

---

spring:
  config:
    activate:
      on-profile: console-test


datasource:
  url: jdbc:h2:tcp://localhost/~/test
  username: sa
  password:

persistenceName: console-test