server:
  port: 5510

---

spring:
  config:
    activate:
      on-profile: db-mysql

datasource:
  url: "jdbc:mysql://localhost:3307/delivery_service"
  username: "root"
  password: "111111"

---

spring:
  config:
    activate:
      on-profile: db-h2
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:test
      username: sa
      password:

datasource:
  url: jdbc:h2:mem:test;MODE=MySQL
  username: sa
  password:

