logging:
  config: classpath:logback-console.xml

---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080
url:
  api: 127.0.0.1:5510
  ui: 127.0.0.1:8080
---

spring:
  config:
    activate:
      on-profile: server
server:
  port: 8081
url:
  api: 127.0.0.1:5511
  ui: 127.0.0.1:8081